# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pr:
- master
- release

pool:
  vmImage: 'windows-2019'

variables:
  solution: 'MaterialDesignToolkit.Wpf.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dotNetCoreVersion: '3.0.x'
  nugetVersionSpec: '5.x.x'

steps:
- task: UseDotNet@2
  displayName: 'Use dotNet $(dotNetCoreVersion)'
  inputs:
    packageType: 'sdk'
    version: '$(dotNetCoreVersion)'

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet $(nugetVersionSpec)'
  inputs:
    versionSpec: '$(nugetVersionSpec)'

- powershell: .paket\paket.exe restore

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: $(solution)

- task: NuGetCommand@2
  displayName: 'NuGet restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '$(solution)'
    arguments: '/p:Configuration=$(buildConfiguration) /p:Platform="Any CPU" /p:MDIXVersion=$(mdixVersion).$(Build.BuildID) /p:MDIXColorsVersion=$(mdixColorsVersion).$(Build.BuildID) /p:MDIXMahAppsVersion=$(mdixMahappsVersion).$(Build.BuildID)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '$(solution)'

- task: PowerShell@2
  displayName: "Build NuGets"
  inputs: 
    filePath: 'Scripts\\BuildNugets.ps1'
    arguments: '-MDIXVersion $(mdixVersion)-ci$(Build.BuildId) -MDIXMahAppsVersion $(mdixMahappsVersion)-ci$(Build.BuildId) -MDIXColorsVersion $(mdixColorsVersion)-ci$(Build.BuildId)'

- task: PublishPipelineArtifact@0
  name: "PublishDemoApp"
  inputs:
    artifactName: 'DemoApp'
    targetPath: 'MainDemo.Wpf/bin/$(buildConfiguration)'

- task: PublishPipelineArtifact@0
  name: "PublishMaterialDesign"
  inputs:
    artifactName: 'MDIX'
    targetPath: 'MaterialDesignThemes.$(mdixVersion)-ci$(Build.BuildId).nupkg'

- task: PublishPipelineArtifact@0
  name: "PublishMaterialDesignColors"
  inputs:
    artifactName: 'MDIX.Colors'
    targetPath: 'MaterialDesignColors.$(mdixColorsVersion)-ci$(Build.BuildId).nupkg'

- task: PublishPipelineArtifact@0
  name: "PublishMaterialDesignMahApps"
  inputs:
    artifactName: 'MDIX.MahApps'
    targetPath: 'MaterialDesignThemes.MahApps.$(mdixMahappsVersion)-ci$(Build.BuildId).nupkg'

- task: PublishPipelineArtifact@0
  name: "PublishScript"
  inputs:
    artifactName: 'Script'
    targetPath: 'Scripts\\UpdateNugets.ps1'